apiVersion: v1
kind: ConfigMap
metadata:
  name: stargit-config
  namespace: stargit
data:
  NODE_ENV: "production"
  GIT_USER: "git"
  GIT_EMAIL: "git@stargit.com"
  API_PORT: "3001"
  SSH_PORT: "22"
  REDIS_URL: "redis://redis-service:6379"
  GIT_REPOSITORIES_PATH: "/var/git/repositories"
  GIT_TEMP_PATH: "/var/git/temp"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: stargit
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream frontend {
            server frontend-service:3000;
        }
        
        upstream backend {
            server backend-service:3001;
        }
        
        server {
            listen 80;
            server_name _;
            
            location / {
                proxy_pass http://frontend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/ {
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
